---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 3
  ansible_sudo: false
#  require_chef_for_busser: false
#  require_ruby_for_busser: true
  hosts: all

platforms:
  - name: ubuntu-14.04

  - name: centos-6.5
    provisioner:
      ansible_yum_repo: https://download.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
  - name: centos-7.0
    provisioner:
      ansible_yum_repo: https://download.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
suites:
  - name: default
