---
- name: ensure necessary yum packages are installed
  yum:
    name: "{{ item }}"
    state: present
  sudo: true
  with_items: rvm.redhat_packages
  when: ansible_os_family == "RedHat"

- name: ensure necessary apt packages are installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  sudo: true
  with_items: rvm.debian_packages
  when: ansible_os_family == "Debian"
